name: Windows

on:
  push:
    branches: [master,semaphore]
  pull_request:
    branches: [master]

env:
  BOOST_ROOT: "C:/hostedtoolcache/windows/Boost/1.72.0/x86_64"
  BOOST_URL: "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Boost
      run: |
        Write-Host "Downloading Boost to ${{ env.BOOST_ROOT }}"
        C:\msys64\usr\bin\wget.exe -nv "${{ env.BOOST_URL }}" -O "${{ github.workspace }}/boost.exe"
        Start-Process -Wait -FilePath "${{ github.workspace }}/boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=${{ env.BOOST_ROOT }}"
      shell: powershell
    - name: Build Release
      uses: lukka/run-cmake@v3
      with:
        buildDirectory: ${{ github.workspace }}/build/
        cmakeAppendedArgs: '-G Ninja
          -DBOOST_ROOT="${{ env.BOOST_ROOT }}"
          -DBOOST_INCLUDEDIR="${{ env.BOOST_ROOT }}/include"
          -DBOOST_LIBRARYDIR="${{ env.BOOST_ROOT }}/lib"
          -DCMAKE_BUILD_TYPE="Release"'
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        useVcpkgToolchainFile: true
    - name: Test
      working-directory: build
      run: ctest
