name: Windows

on:
  push:
    branches: [master,semaphore]
  pull_request:
    branches: [master]

env:
  BOOST_ROOT: "C:/hostedtoolcache/windows/Boost/1.72.0/x86_64"
  BOOST_URL: "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Boost
      run: |
        Write-Host "Downloading Boost to ${{ env.BOOST_ROOT }}"
        C:\msys64\usr\bin\wget.exe -nv "${{ env.BOOST_URL }}" -O "${{ github.workspace }}/boost.exe"
        Start-Process -Wait -FilePath "${{ github.workspace }}/boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=${{ env.BOOST_ROOT }}"
      shell: powershell
    - name: cmake
      run: |
        cmake -E make_directory build
        cd build
        cmake -DBOOST_ROOT="${env:BOOST_ROOT_1_72_0}" -DCOMPILE_TESTS=ON ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j2 
    - name: Test
      working-directory: build
      run: ctest -C Debug -j2 --output-on-failure
